custom:
  baseurl : ${BASE_URL}
  expire: ${EXPIRE_TIME}
server:
  port: ${PORT}


spring:
  data:
    mongodb:
      uri: mongodb://${SPRING_DATA_MONGO_USER}:${SPRING_DATA_MONGO_PASSWORD}@${SPRING_DATA_MONGO_HOST}:27017/
      auto-index-creation: true
      database: ${SPRING_DATA_MONGO_DATABASE}