apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: alirezaak2000/urlshortener:1.1
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: SPRING_DATA_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: BASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: PORT
            - name: EXPIRE_TIME
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: EXPIRE_TIME
            - name: SPRING_DATA_MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: SPRING_DATA_MONGO_HOST
            - name: SPRING_DATA_MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: SPRING_DATA_MONGO_DATABASE
